#!/bin/bash
#sudo apt update && sudo apt upgrade -y
#apt install cron
#apt install iputils-ping 
#apt install cron
#timedatectl set-timezone Asia/Bangkok



sh <(curl https://cyberpanel.net/install.sh || wget -O - https://cyberpanel.net/install.sh)
Usage: sh <(curl cyberpanel.sh) --argument

-v or --version : choose to install CyberPanel OpenLiteSpeed or CyberPanel Enterprise, available options are ols , TRIAL and SERIAL_NUMBER, default ols
Please be aware, this serial number must be obtained from LiteSpeed Store.
And if this serial number has been used before, it must be released/migrated in Store first, otherwise it will fail to start.

-a or --addons : install addons: memcached, redis, PHP extension for memcached and redis

-p or --password : set password of new installation, empty for default 1234567, [r] or [random] for randomly generated 16 digital password, any other value besides [d] and [r(andom)] will be accept as password, default use 1234567.
e.g. -p r will generate a random password
     -p 123456789 will set password to 123456789

-m or --minimal : set to minimal mode which will not install PowerDNS, Pure-FTPd and Postfix

-m postfix/pureftpd/powerdns will do minimal install also with compoenent given
e.g.  -m postfix will do minimal install also with Postfix
      -m powerdns will do minimal install also with PowerDNS
      -m postfix powerdns will do minimal install also with Postfix and PowerDNS

-b or --branch : install with given branch/version , must be higher than 1.9.4
e.g.  -b 2.0.2 will install 2.0.2 version

--mirror : this argument force to use mirror server for majority of repositories, only suggest to use for servers within China

Example:

sh <(curl cyberpanel.sh) -v ols -p r or ./cyberpanel.sh --version ols --password random

This will install CyberPanel OpenLiteSpeed and randomly generate the password.

sh <(curl cyberpanel.sh) -v LICENSE_KEY -a -p my_pass_word

This will install LiteSpeed Enterise , replace LICENSE_KEY to actual license key and set password to my_pass_word
